/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test
    fun appHasAGreeting() {
        val greeting = "EzyMap Backend API is running!"
        assertNotNull(greeting, "app should have a greeting")
    }
}
